services:
  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: mysql_fruit_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fruit_db
      MYSQL_USER: user_jessica
      MYSQL_PASSWORD: password_jessica
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fruit_network

  app:
    build: .
    container_name: spring_fruit_api
    ports:
      - "9000:9000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: fruit_db
      DB_USERNAME: user_jessica
      DB_PASSWORD: password_jessica

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fruit_network

networks:
  fruit_network:
    driver: bridge

volumes:
  mysql_data: